receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  logging: {}
  file:
    path: ./test_data.json

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging, file]
      processors: [batch, queued_retry]
