receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  logging: {}
  # sentry:
  #   dsn: "https://key@host:port/1"
  jaeger_thrift:
    url: "http://some.location:14268/api/traces"
  file:
    path: ./test_data.json

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging, sentry]
      processors: [batch, queued_retry]
