version: '3'

services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Flask
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3003:30003
    environment:
      PORT: 3003
      FLASK_ENV: 'test'
