version: '3'

services:
  # Flask
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      FLASK_ENV: 'test'

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14268"
      - "14250"
    depends_on:
      - flask

  # Collector
  collector:
    image: omnition/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "55678:55678"
    depends_on:
      - jaeger-all-in-one
