receivers:
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  logging:
  sentry:
    dsn: http://48b95f02bef84e17abde966511294457@host.docker.internal:8000/8 # replace this with your own DSN

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging, sentry]
      processors: [batch, queued_retry]
