receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
  zipkin:
    endpoint: :9411
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14268"

exporters:
  opencensus:
    endpoint: "otel-collector:55678"
  logging:
    loglevel: debug
  sentry:
    dsn: http://48b95f02bef84e17abde966511294457@host.docker.internal:8000/8 # replace with your own DSN

processors:
  batch:
  queued_retry:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [opencensus, jaeger, zipkin]
      exporters: [opencensus, logging, sentry]
      processors: [batch, queued_retry]
