receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  logging: {}
  sentry:
    dsn: # INSERT DSN HERE

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging, sentry]
      processors: [batch, queued_retry]
