receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  logging: {}
  sentry:
    dsn: http://69e5dabe7bf446d78ee18dbbe133480e@o1.ingest.localhost:8000/8 # Replace this with your own DSN

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging, sentry]
      processors: [batch, queued_retry]
